# Generated by Django 3.2.12 on 2022-03-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_sales', '0002_invoice_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='downpayment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Down Payment'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payable',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Payable'),
        ),
    ]
