# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\.\couchbase_version.py
# at
#    2023-03-09 09:17:26.331761
__version__ = '4.1.3'