# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.settings_typecode_body import SettingsTypecodeBody  # noqa: E501
from ib_web_api.rest import ApiException


class TestSettingsTypecodeBody(unittest.TestCase):
    """SettingsTypecodeBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsTypecodeBody(self):
        """Test SettingsTypecodeBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.settings_typecode_body.SettingsTypecodeBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
