"""MyrtDesk backlight constants"""

DOMAIN_BACKLIGHT = 1

COMMAND_READ_STATE = 0
COMMAND_SET_EFFECT = 1
COMMAND_SET_EFFECT_DATA = 2
COMMAND_SET_COLOR = 3
COMMAND_SET_WHITE = 4
COMMAND_SET_BRIGHTNESS = 5
COMMAND_SET_POWER = 6
COMMAND_FIRMWARE_RECEIVE = 7
COMMAND_FIRMWARE_FRAME = 8
COMMAND_FIRMWARE_APPLY = 9
