# Generated by Django 4.1.3 on 2023-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlWithAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, verbose_name="User name")),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Key"
                    ),
                ),
                (
                    "redirect_to",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Redirect to",
                    ),
                ),
                (
                    "post_data",
                    models.TextField(
                        blank=True, editable=False, null=True, verbose_name="Post data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Url with authorization",
                "verbose_name_plural": "Urls with authorization",
                "ordering": ["id"],
                "default_permissions": ("add", "change", "delete", "list"),
            },
        ),
    ]
