# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2006(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'm': 'int',
        'e': 'list[InlineResponse2006E]'
    }

    attribute_map = {
        'm': 'M',
        'e': 'E'
    }

    def __init__(self, m=None, e=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger"""  # noqa: E501
        self._m = None
        self._e = None
        self.discriminator = None
        if m is not None:
            self.m = m
        if e is not None:
            self.e = e

    @property
    def m(self):
        """Gets the m of this InlineResponse2006.  # noqa: E501

        Email option is enabled or not 0-off, 1-on.  # noqa: E501

        :return: The m of this InlineResponse2006.  # noqa: E501
        :rtype: int
        """
        return self._m

    @m.setter
    def m(self, m):
        """Sets the m of this InlineResponse2006.

        Email option is enabled or not 0-off, 1-on.  # noqa: E501

        :param m: The m of this InlineResponse2006.  # noqa: E501
        :type: int
        """

        self._m = m

    @property
    def e(self):
        """Gets the e of this InlineResponse2006.  # noqa: E501


        :return: The e of this InlineResponse2006.  # noqa: E501
        :rtype: list[InlineResponse2006E]
        """
        return self._e

    @e.setter
    def e(self, e):
        """Sets the e of this InlineResponse2006.


        :param e: The e of this InlineResponse2006.  # noqa: E501
        :type: list[InlineResponse2006E]
        """

        self._e = e

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
