# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.inline_response20027_amount import InlineResponse20027Amount  # noqa: E501
from ib_web_api.rest import ApiException


class TestInlineResponse20027Amount(unittest.TestCase):
    """InlineResponse20027Amount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20027Amount(self):
        """Test InlineResponse20027Amount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.inline_response20027_amount.InlineResponse20027Amount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
