from myadmin.views import index # / index
from framework.static import serve #  None
from myadmin.views import login # /myadmin/login myadmin.login
from myadmin.views import logout # /myadmin/logout myadmin.logout
from myadmin.views import register # /myadmin/register myadmin.register
from myadmin.views.test import test_mysql # /test_mysql myadmin.test.test_mysql
from ws_gateway.views import js # /ws_gateway/js ws_gateway.js
from analysis.views.query import interface #  analysis.query.interface
from analysis.views.statistic import statistic_list # /analysis/statistic/list analysis.statistic.statistic_list
from dynamic_settings.views import list # /dynamic_settings/list dynamic_settings.list
from analysis.views.query import query_widget #  analysis.query.query_widget
from analysis.views.statistic import statistic_edit # /analysis/statistic/edit analysis.statistic.statistic_edit
from analysis.views.statistic import statistic_save # /analysis/statistic/save analysis.statistic.statistic_save
from sync_model.views import backstage_list # /sync/backstage/list sync_model.backstage_list
from dynamic_settings.views import save # /dynamic_settings/save dynamic_settings.save
from myadmin.views import index # /myadmin/index myadmin.index
from analysis.views.statistic import statistic_remove # /analysis/statistic/remove analysis.statistic.statistic_remove
from sync_model.views import backstage_list # /sync/backstage/list sync_model.backstage_list
from myadmin.views.sms import send_verification_code # /myadmin/sms/send_verification_code myadmin.sms.send_verification_code
from analysis.views.query import query_view # /query/view analysis.query.query_view
from analysis.views.query import template_edit # /analysis/query/template_edit analysis.query.template_edit
from analysis.views.statistic import test_query # /analysis/statistic/test_query analysis.statistic.test_query
from myadmin.views.test import test # /test myadmin.test
from analysis.views.query import query_view # /query/view analysis.query.query_view
from analysis.views.statistic import statistic_execute # /analysis/statistic/execute analysis.statistic.statistic_execute
from upload.views import upload # /upload upload
from analysis.views.query import query_view # /query/view analysis.query.query_view
from sync_model.views import backstage_edit # /sync/backstage/edit sync_model.backstage_edit
from log_def.views import interface # /log/dict/interface log_def.interface
from sync_model.views import backstage_remove # /sync/backstage/remove sync_model.backstage_remove
from analysis.views.query import query_view # /query/view analysis.query.query_view
from analysis.views.query import query_clear_cache # /analysis/query/clear/cache analysis.query.query_clear_cache
from myadmin.views import phone_login # /myadmin/phone_login myadmin.phone_login
from upload.views import new_upload # /new/upload upload.new_upload
from sync_model.views import backstage_push # /sync/backstage/push sync_model.backstage_push
from ws_gateway.views import test # /ws_gateway/test ws_gateway.test
from sync_model.views import do_backstage_sync # /sync/backstage/dosync sync_model.do_backstage_sync
from myadmin.views.verify import get_verify_code_image # /get_verify_code_image/ myadmin.verify.get_verify_code_image
from sync_model.views import get_remote_push_data # /sync/backstage/remotedb sync_model.get_remote_push_data
from framework.views import I18n;I18n.metadata;I18n.metadata # /i18n/metadata i18n.metadata
from framework.views import I18n;I18n.js # /i18n/js i18n.js
from framework.views import I18n;I18n.set_language # /i18n/set_language i18n.set_language
from myadmin.views.user_info import UserInfoSet;UserInfoSet.list # /myadmin/user_info/list myadmin.user_info.list
from myadmin.views.user_info import UserInfoSet;UserInfoSet.save # /myadmin/user_info/save myadmin.user_info.save
from myadmin.views.user_info import UserInfoSet;UserInfoSet.delete # /myadmin/user_info/delete myadmin.user_info.delete
from myadmin.views.user_info import UserInfoSet;UserInfoSet.edit # /myadmin/user_info/edit myadmin.user_info.edit
from myadmin.views.user_info import UserInfoSet;UserInfoSet.metadata;UserInfoSet.metadata # /myadmin/user_info/metadata myadmin.user_info.metadata
from myadmin.views.user_info import UserInfoSet;UserInfoSet.edit_self # /myadmin/user_info/edit_self myadmin.user_info.edit_self
from myadmin.views.user_info import UserInfoSet;UserInfoSet.save_self # /myadmin/user_info/save_self myadmin.user_info.save_self
from myadmin.views.user import UserSet;UserSet.list # /myadmin/user/list myadmin.user.list
from myadmin.views.user import UserSet;UserSet.save # /myadmin/user/save myadmin.user.save
from myadmin.views.user import UserSet;UserSet.delete # /myadmin/user/delete myadmin.user.delete
from myadmin.views.user import UserSet;UserSet.edit # /myadmin/user/edit myadmin.user.edit
from myadmin.views.user import UserSet;UserSet.metadata;UserSet.metadata # /myadmin/user/metadata myadmin.user.metadata
from myadmin.views.user import UserSet;UserSet.change_password;UserSet.change_password # /myadmin/user/change_password myadmin.user.change_password
from myadmin.views.user import UserSet;UserSet.change_status # /myadmin/user/change_status myadmin.user.change_status
from myadmin.views.user import UserSet;UserSet.impersonate;UserSet.impersonate # /myadmin/user/impersonate myadmin.user.impersonate
from myadmin.views.resource import ResourceSet;ResourceSet.list # /myadmin/resource/list myadmin.resource.list
from myadmin.views.resource import ResourceSet;ResourceSet.save # /myadmin/resource/save myadmin.resource.save
from myadmin.views.resource import ResourceSet;ResourceSet.delete # /myadmin/resource/delete myadmin.resource.delete
from myadmin.views.resource import ResourceSet;ResourceSet.edit # /myadmin/resource/edit myadmin.resource.edit
from myadmin.views.resource import ResourceSet;ResourceSet.metadata;ResourceSet.metadata # /myadmin/resource/metadata myadmin.resource.metadata
from myadmin.views.role import RoleSet;RoleSet.list # /myadmin/role/list myadmin.role.list
from myadmin.views.role import RoleSet;RoleSet.save # /myadmin/role/save myadmin.role.save
from myadmin.views.role import RoleSet;RoleSet.delete # /myadmin/role/delete myadmin.role.delete
from myadmin.views.role import RoleSet;RoleSet.edit # /myadmin/role/edit myadmin.role.edit
from myadmin.views.role import RoleSet;RoleSet.metadata;RoleSet.metadata # /myadmin/role/metadata myadmin.role.metadata
from myadmin.views.role import RoleSet;RoleSet.resource_members # /myadmin/role/resource_members myadmin.role.resource_members
from myadmin.views.role import RoleSet;RoleSet.update # /myadmin/role/update myadmin.role.update
from myadmin.views.menu import MenuSet;MenuSet.list # /myadmin/menu/list myadmin.menu.list
from myadmin.views.menu import MenuSet;MenuSet.save # /myadmin/menu/save myadmin.menu.save
from myadmin.views.menu import MenuSet;MenuSet.delete # /myadmin/menu/delete myadmin.menu.delete
from myadmin.views.menu import MenuSet;MenuSet.edit # /myadmin/menu/edit myadmin.menu.edit
from myadmin.views.menu import MenuSet;MenuSet.metadata;MenuSet.metadata # /myadmin/menu/metadata myadmin.menu.metadata
from myadmin.views.menu import MenuSet;MenuSet.update_menu;MenuSet.update_menu # /myadmin/menu/update_menu myadmin.menu.update_menu
from myadmin.views.operate_log import OperateLogSet;OperateLogSet.list # /myadmin/operate_log/list myadmin.operate_log.list
from myadmin.views.operate_log import OperateLogSet;OperateLogSet.save # /myadmin/operate_log/save myadmin.operate_log.save
from myadmin.views.operate_log import OperateLogSet;OperateLogSet.delete # /myadmin/operate_log/delete myadmin.operate_log.delete
from myadmin.views.operate_log import OperateLogSet;OperateLogSet.edit # /myadmin/operate_log/edit myadmin.operate_log.edit
from myadmin.views.operate_log import OperateLogSet;OperateLogSet.metadata;OperateLogSet.metadata # /myadmin/operate_log/metadata myadmin.operate_log.metadata
from analysis.views.query import QuerySet;QuerySet.list # /analysis/query/list analysis.query.list
from analysis.views.query import QuerySet;QuerySet.save # /analysis/query/save analysis.query.save
from analysis.views.query import QuerySet;QuerySet.delete # /analysis/query/delete analysis.query.delete
from analysis.views.query import QuerySet;QuerySet.edit # /analysis/query/edit analysis.query.edit
from analysis.views.query import QuerySet;QuerySet.metadata;QuerySet.metadata # /analysis/query/metadata analysis.query.metadata
from analysis.views.query_server import QueryServerSet;QueryServerSet.list # /analysis/query_server/list analysis.query_server.list
from analysis.views.query_server import QueryServerSet;QueryServerSet.save # /analysis/query_server/save analysis.query_server.save
from analysis.views.query_server import QueryServerSet;QueryServerSet.delete # /analysis/query_server/delete analysis.query_server.delete
from analysis.views.query_server import QueryServerSet;QueryServerSet.edit # /analysis/query_server/edit analysis.query_server.edit
from analysis.views.query_server import QueryServerSet;QueryServerSet.metadata;QueryServerSet.metadata # /analysis/query_server/metadata analysis.query_server.metadata
from analysis.views.query_server import QueryServerSet;QueryServerSet.test_connect # /analysis/query_server/test_connect analysis.query_server.test_connect
from celery_task.views import CeleryTask;CeleryTask.metadata;CeleryTask.metadata # /celery_task/metadata celery_task.metadata
from celery_task.views import CeleryTask;CeleryTask.js # /celery_task/js celery_task.js
from celery_task.views import CeleryTask;CeleryTask.query # /celery_task/query celery_task.query
from celery_task.views import CeleryTask;CeleryTask.query_progress # /celery_task/query_progress celery_task.query_progress
from celery_task.views import CeleryTask;CeleryTask.revoke_task # /celery_task/revoke_task celery_task.revoke_task
from celery_task.views import CeleryTask;CeleryTask.tasks # /celery_task/tasks celery_task.tasks
from celery_task.views import CeleryTask;CeleryTask.test # /celery_task/test celery_task.test
from celery_task.views.periodic_task import PeriodicTaskSet;PeriodicTaskSet.list # /celery_task/periodic_task/list celery_task.periodic_task.list
from celery_task.views.periodic_task import PeriodicTaskSet;PeriodicTaskSet.save # /celery_task/periodic_task/save celery_task.periodic_task.save
from celery_task.views.periodic_task import PeriodicTaskSet;PeriodicTaskSet.delete # /celery_task/periodic_task/delete celery_task.periodic_task.delete
from celery_task.views.periodic_task import PeriodicTaskSet;PeriodicTaskSet.edit # /celery_task/periodic_task/edit celery_task.periodic_task.edit
from celery_task.views.periodic_task import PeriodicTaskSet;PeriodicTaskSet.metadata;PeriodicTaskSet.metadata # /celery_task/periodic_task/metadata celery_task.periodic_task.metadata
from celery_task.views.solar_schedule import SolarScheduleSet;SolarScheduleSet.list # /celery_task/solar_schedule/list celery_task.solar_schedule.list
from celery_task.views.solar_schedule import SolarScheduleSet;SolarScheduleSet.save # /celery_task/solar_schedule/save celery_task.solar_schedule.save
from celery_task.views.solar_schedule import SolarScheduleSet;SolarScheduleSet.delete # /celery_task/solar_schedule/delete celery_task.solar_schedule.delete
from celery_task.views.solar_schedule import SolarScheduleSet;SolarScheduleSet.edit # /celery_task/solar_schedule/edit celery_task.solar_schedule.edit
from celery_task.views.solar_schedule import SolarScheduleSet;SolarScheduleSet.metadata;SolarScheduleSet.metadata # /celery_task/solar_schedule/metadata celery_task.solar_schedule.metadata
from celery_task.views.clocked_schedule import ClockedScheduleSet;ClockedScheduleSet.list # /celery_task/clocked_schedule/list celery_task.clocked_schedule.list
from celery_task.views.clocked_schedule import ClockedScheduleSet;ClockedScheduleSet.save # /celery_task/clocked_schedule/save celery_task.clocked_schedule.save
from celery_task.views.clocked_schedule import ClockedScheduleSet;ClockedScheduleSet.delete # /celery_task/clocked_schedule/delete celery_task.clocked_schedule.delete
from celery_task.views.clocked_schedule import ClockedScheduleSet;ClockedScheduleSet.edit # /celery_task/clocked_schedule/edit celery_task.clocked_schedule.edit
from celery_task.views.clocked_schedule import ClockedScheduleSet;ClockedScheduleSet.metadata;ClockedScheduleSet.metadata # /celery_task/clocked_schedule/metadata celery_task.clocked_schedule.metadata
from celery_task.views.crontab_schedule import CrontabScheduleSet;CrontabScheduleSet.list # /celery_task/crontab_schedule/list celery_task.crontab_schedule.list
from celery_task.views.crontab_schedule import CrontabScheduleSet;CrontabScheduleSet.save # /celery_task/crontab_schedule/save celery_task.crontab_schedule.save
from celery_task.views.crontab_schedule import CrontabScheduleSet;CrontabScheduleSet.delete # /celery_task/crontab_schedule/delete celery_task.crontab_schedule.delete
from celery_task.views.crontab_schedule import CrontabScheduleSet;CrontabScheduleSet.edit # /celery_task/crontab_schedule/edit celery_task.crontab_schedule.edit
from celery_task.views.crontab_schedule import CrontabScheduleSet;CrontabScheduleSet.metadata;CrontabScheduleSet.metadata # /celery_task/crontab_schedule/metadata celery_task.crontab_schedule.metadata
from celery_task.views.interval_schedule import IntervalScheduleSet;IntervalScheduleSet.list # /celery_task/interval_schedule/list celery_task.interval_schedule.list
from celery_task.views.interval_schedule import IntervalScheduleSet;IntervalScheduleSet.save # /celery_task/interval_schedule/save celery_task.interval_schedule.save
from celery_task.views.interval_schedule import IntervalScheduleSet;IntervalScheduleSet.delete # /celery_task/interval_schedule/delete celery_task.interval_schedule.delete
from celery_task.views.interval_schedule import IntervalScheduleSet;IntervalScheduleSet.edit # /celery_task/interval_schedule/edit celery_task.interval_schedule.edit
from celery_task.views.interval_schedule import IntervalScheduleSet;IntervalScheduleSet.metadata;IntervalScheduleSet.metadata # /celery_task/interval_schedule/metadata celery_task.interval_schedule.metadata
from celery_task.views.task_result import TaskResultSet;TaskResultSet.list # /celery_task/task_result/list celery_task.task_result.list
from celery_task.views.task_result import TaskResultSet;TaskResultSet.save # /celery_task/task_result/save celery_task.task_result.save
from celery_task.views.task_result import TaskResultSet;TaskResultSet.delete # /celery_task/task_result/delete celery_task.task_result.delete
from celery_task.views.task_result import TaskResultSet;TaskResultSet.edit # /celery_task/task_result/edit celery_task.task_result.edit
from celery_task.views.task_result import TaskResultSet;TaskResultSet.metadata;TaskResultSet.metadata # /celery_task/task_result/metadata celery_task.task_result.metadata
from log_def.views.log_define import LogDefineSet;LogDefineSet.list # /log_def/log_define/list log_def.log_define.list
from log_def.views.log_define import LogDefineSet;LogDefineSet.save # /log_def/log_define/save log_def.log_define.save
from log_def.views.log_define import LogDefineSet;LogDefineSet.delete # /log_def/log_define/delete log_def.log_define.delete
from log_def.views.log_define import LogDefineSet;LogDefineSet.edit # /log_def/log_define/edit log_def.log_define.edit
from log_def.views.log_define import LogDefineSet;LogDefineSet.metadata;LogDefineSet.metadata # /log_def/log_define/metadata log_def.log_define.metadata
from log_def.views.dict_define import DictDefineSet;DictDefineSet.list # /log_def/dict_define/list log_def.dict_define.list
from log_def.views.dict_define import DictDefineSet;DictDefineSet.save # /log_def/dict_define/save log_def.dict_define.save
from log_def.views.dict_define import DictDefineSet;DictDefineSet.delete # /log_def/dict_define/delete log_def.dict_define.delete
from log_def.views.dict_define import DictDefineSet;DictDefineSet.edit # /log_def/dict_define/edit log_def.dict_define.edit
from log_def.views.dict_define import DictDefineSet;DictDefineSet.metadata;DictDefineSet.metadata # /log_def/dict_define/metadata log_def.dict_define.metadata
from log_def.views.dict_define import DictDefineSet;DictDefineSet.interface # /log_def/dict_define/interface log_def.dict_define.interface
from drf_yasg.views.get_schema_view.<locals> import SchemaView #  schema-json
from drf_yasg.views.get_schema_view.<locals> import SchemaView # /api/swagger schema-swagger-ui
from drf_yasg.views.get_schema_view.<locals> import SchemaView # /api/redoc schema-redoc
from framework.static import serve #  None
from debug_toolbar.views import render_panel #  render_panel
from debug_toolbar.panels.history.views import history_sidebar #  history_sidebar
from debug_toolbar.panels.history.views import history_refresh #  history_refresh
from debug_toolbar.panels.sql.views import sql_select #  sql_select
from debug_toolbar.panels.sql.views import sql_explain #  sql_explain
from debug_toolbar.panels.sql.views import sql_profile #  sql_profile
from debug_toolbar.panels.templates.views import template_source #  template_source