DELETE FROM ENTRY_ENTITY WHERE OWNER = 'default';
DELETE FROM ENTRY_PATH WHERE OWNER = 'default';
DELETE FROM ENTRY_DATASET_RELATIONSHIPS WHERE OWNER = 'default';
DELETE FROM ENTRY_ORDER WHERE OWNER = 'default';
DELETE FROM ENTRY_FILTERS WHERE OWNER = 'default';
DELETE FROM ENTRY_HAVING WHERE OWNER = 'default';
delete from ENTRY_AGGREGATORS where OWNER='default';
DELETE FROM ENTRY_DATASET_MAPPINGS where OWNER = 'default';

INSERT INTO ENTRY_ENTITY(COD_ENTITY, TABLE_NAME, ENTITY_TYPE, COD_PATH, STRATEGY, OWNER) VALUES
-- Sources
('ET_AIRCRAFTS', 'AIRCRAFTS','SRC', 'PSA', NULL, 'default'),
('ET_AIRPORTS', 'AIRPORTS','SRC', 'PSA', NULL, 'default'),
('ET_CARRIERS', 'CARRIERS','SRC', 'PSA', NULL, 'default'),
('ET_FLIGHTS', 'FLIGHTS','SRC', 'PSA', NULL, 'default'),
('ET_CUSTOMERS', 'CUSTOMERS','SRC', 'PSA', NULL, 'default'),
('ET_USERS_WEB', 'USERS_WEB','SRC', 'PSA', NULL, 'default'),
-- Transformation
('ET_USERS_WEB_TMP', 'USERS_WEB_TMP', 'WITH', 'NPSA',NULL, 'default'),
('ET_FLIGHTS_TMP', 'FLIGHTS_TMP','TB', 'NPSA', 'INSERT', 'default'),
('ET_AIRCRAFTS_TMP', 'AIRCRAFTS_TMP','TB', 'NPSA', 'INSERT', 'default'),
('ET_CUSTOMERS_TMP', 'CUSTOMERS_TMP', 'TB', 'NPSA', 'INSERT', 'default');

INSERT INTO ENTRY_PATH (COD_PATH, DATABASE_NAME, SCHEMA_NAME, OWNER) VALUES
('PSA', 'MAIN', NULL, 'default'),
('NPSA', 'MAIN', NULL, 'default'),
('RDV', 'MAIN', NULL, 'default');

INSERT INTO ENTRY_DATASET_RELATIONSHIPS (COD_ENTITY_MASTER, COLUMN_NAME_MASTER, COD_ENTITY_DETAIL, COLUMN_NAME_DETAIL, RELATIONSHIP_TYPE, OWNER) VALUES
('ET_AIRCRAFTS', 'CARRIER_IATA', 'ET_CARRIERS', 'IATA', 'MASTER JOIN', 'default'),
('ET_CUSTOMERS', 'FLIGHT_CODE', 'ET_FLIGHTS', 'FLIGHT_CODE', 'MASTER JOIN', 'default'),
('ET_USERS_WEB_TMP', 'ID_CUSTOMER', 'ET_CUSTOMERS', 'ID_CUSTOMER', 'DETAIL JOIN', 'default');

INSERT INTO ENTRY_ORDER (COD_ENTITY_TARGET,COD_ENTITY_SOURCE, COLUMN_NAME,NUM_BRANCH, ORDER_TYPE, OWNER) VALUES
('ET_FLIGHTS_TMP','ET_FLIGHTS', 'UNIQUE_FLIGHT_CODE', 1, 'ASC', 'default'),
('ET_FLIGHTS_TMP','ET_FLIGHTS', 'FLIGHT_CODE', 1, 'DESC', 'default');

INSERT INTO ENTRY_FILTERS (COD_ENTITY_TARGET, VALUE, NUM_BRANCH, OWNER) VALUES
('ET_CUSTOMERS_TMP', 'TIME_ONLINE_SECONDS > 0', 1, 'default');

INSERT INTO ENTRY_AGGREGATORS (COD_ENTITY_TARGET, COD_ENTITY_SOURCE, COLUMN_NAME, NUM_BRANCH, OWNER) VALUES
('ET_USERS_WEB_TMP','ET_USERS_WEB', 'ID_CUSTOMER', 1, 'default');

INSERT INTO ENTRY_DATASET_MAPPINGS (COD_ENTITY_SOURCE,VALUE_SOURCE,COD_ENTITY_TARGET,COLUMN_NAME_TARGET,COLUMN_TYPE_TARGET,ORDINAL_POSITION,"LENGTH","PRECISION",NUM_BRANCH,"KEY_TYPE",SW_DISTINCT,OWNER) VALUES
('ET_USERS_WEB','ID_CUSTOMER','ET_USERS_WEB_TMP','ID_CUSTOMER','INTEGER',1,50,0,1,'PK',0,'default'),
('ET_USERS_WEB','MIN(VISIT_DATE)','ET_USERS_WEB_TMP','FIRST_APPEAR_DATE','TEXT',2,50,0,1,NULL,0,'default'),
('ET_USERS_WEB','MAX(VISIT_DATE)','ET_USERS_WEB_TMP','LAST_APPEAR_DATE','TEXT',3,50,0,1,NULL,0,'default'),
('ET_USERS_WEB','SUM(TIME_ONLINE_SECONDS)','ET_USERS_WEB_TMP','TIME_ONLINE_SECONDS','INTEGER',4,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','UNIQUE_FLIGHT_CODE','ET_FLIGHTS_TMP','UNIQUE_FLIGHT_CODE','TEXT',1,50,0,1,'PK',0,'default'),
('ET_FLIGHTS','SUBSTR(FLIGHT_CODE,1,3)','ET_FLIGHTS_TMP','ICAO_CARRIER_CODE','TEXT',2,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','FLIGHT_CODE','ET_FLIGHTS_TMP','FLIGHT_CODE','TEXT',3,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','AIRPORT_ORIGIN_CODE','ET_FLIGHTS_TMP','AIRPORT_ORIGIN_CODE','TEXT',4,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','AIRPORT_DEST_CODE','ET_FLIGHTS_TMP','AIRPORT_DEST_CODE','TEXT',5,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','DEPARTURE_GATE','ET_FLIGHTS_TMP','DEPARTURE_GATE','TEXT',6,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','BOARDING_TIME','ET_FLIGHTS_TMP','BOARDING_TIME','TEXT',7,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','DEPARTURE_TIME','ET_FLIGHTS_TMP','DEPARTURE_TIME','TEXT',8,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','LANDING_TIME','ET_FLIGHTS_TMP','LANDING_TIME','TEXT',9,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','ARRIVAL_TIME','ET_FLIGHTS_TMP','ARRIVAL_TIME','TEXT',10,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','AIRCRAFT','ET_FLIGHTS_TMP','AIRCRAFT','TEXT',11,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','BOARDING_TIME_REAL','ET_FLIGHTS_TMP','BOARDING_TIME_REAL','TEXT',12,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','DEPARTURE_TIME_REAL','ET_FLIGHTS_TMP','DEPARTURE_TIME_REAL','TEXT',13,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','LANDING_TIME_REAL','ET_FLIGHTS_TMP','LANDING_TIME_REAL','TEXT',14,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','ARRIVAL_TIME_REAL','ET_FLIGHTS_TMP','ARRIVAL_TIME_REAL','TEXT',15,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','OPERATION','ET_FLIGHTS_TMP','OPERATION','TEXT',16,50,0,1,NULL,0,'default'),
('','DATE(''now'')','ET_FLIGHTS_TMP','DATE_CREATED','TEXT',17,50,0,1,NULL,0,'default'),
('','''metamorf_processor''','ET_FLIGHTS_TMP','CREATED_BY','TEXT',18,50,0,1,NULL,0,'default'),
('ET_AIRCRAFTS','LICENSE','ET_AIRCRAFTS_TMP','LICENSE','TEXT',1,50,0,1,'PK',1,'default'),
('ET_AIRCRAFTS','MODEL_ICAO','ET_AIRCRAFTS_TMP','MODEL_ICAO','TEXT',2,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','NAME','ET_AIRCRAFTS_TMP','NAME','TEXT',3,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','AIRCRAFTS_BY','ET_AIRCRAFTS_TMP','AIRCRAFTS_BY','TEXT',4,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','AIRCRAFTS_TYPE','ET_AIRCRAFTS_TMP','AIRCRAFTS_TYPE','TEXT',5,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','APC','ET_AIRCRAFTS_TMP','APC','TEXT',6,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','WTC','ET_AIRCRAFTS_TMP','WTC','TEXT',7,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','ALTERNATIVE_NAME','ET_AIRCRAFTS_TMP','ALTERNATIVE_NAME','TEXT',8,50,0,1,NULL,1,'default'),
('ET_AIRCRAFTS','CARRIER_IATA','ET_AIRCRAFTS_TMP','CARRIER_IATA','TEXT',9,50,0,1,NULL,1,'default'),
('ET_CARRIERS','ICAO','ET_AIRCRAFTS_TMP','ICAO','TEXT',10,50,0,1,NULL,1,'default'),
('','DATE(''now'')','ET_AIRCRAFTS_TMP','DATE_CREATED','TEXT',11,50,0,1,NULL,1,'default'),
('','''metamorf_processor''','ET_AIRCRAFTS_TMP','CREATED_BY','TEXT',12,50,0,1,NULL,1,'default'),
('ET_CUSTOMERS','ID_CUSTOMER','ET_CUSTOMERS_TMP','ID_CUSTOMER','INTEGER',1,50,0,1,'PK',0,'default'),
('ET_CUSTOMERS','NAME','ET_CUSTOMERS_TMP','NAME','INTEGER',2,50,0,1,NULL,0,'default'),
('ET_CUSTOMERS','NIE','ET_CUSTOMERS_TMP','NIE','NAME',3,50,0,1,NULL,0,'default'),
('ET_CUSTOMERS','PRICE','ET_CUSTOMERS_TMP','PRICE','INTEGER',4,50,0,1,NULL,0,'default'),
('ET_CUSTOMERS','SELL_DATE','ET_CUSTOMERS_TMP','SELL_DATE','TEXT',5,50,0,1,NULL,0,'default'),
('ET_CUSTOMERS','ADDRESS','ET_CUSTOMERS_TMP','ADDRESS','TEXT',6,50,0,1,NULL,0,'default'),
('ET_CUSTOMERS','NATIONALITY','ET_CUSTOMERS_TMP','NATIONALITY','TEXT',7,50,0,1,NULL,0,'default'),
('ET_FLIGHTS','UNIQUE_FLIGHT_CODE','ET_CUSTOMERS_TMP','UNIQUE_FLIGHT_CODE','TEXT',8,50,0,1,NULL,0,'default'),
('ET_USERS_WEB_TMP','TIME_ONLINE_SECONDS','ET_CUSTOMERS_TMP','TIME_ONLINE_SECONDS','INTEGER',9,50,0,1,NULL,0,'default'),
('ET_USERS_WEB_TMP','FIRST_APPEAR_DATE','ET_CUSTOMERS_TMP','FIRST_APPEAR_DATE','TEXT',10,50,0,1,NULL,0,'default'),
('ET_USERS_WEB_TMP','LAST_APPEAR_DATE','ET_CUSTOMERS_TMP','LAST_APPEAR_DATE','TEXT',11,50,0,1,NULL,0,'default'),
('','DATE(''now'')','ET_CUSTOMERS_TMP','DATE_CREATED','TEXT',12,50,0,1,NULL,0,'default'),
('','''metamorf_processor''','ET_CUSTOMERS_TMP','CREATED_BY','TEXT',13,50,0,1,NULL,0,'default');


