VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('12')
VERSION_HOUR = int('23')
VERSION_MINUTE = int('18')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202303122318
version_date = '2023/03/12 23:18'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
