
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-10T20:31:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1207dbaee398d6f3ba08cb0777534f071b1e57bc",
 "version": "0.30.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
