# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ib_web_api
from ib_web_api.models.inline_response20029_instrument_list import InlineResponse20029InstrumentList  # noqa: E501
from ib_web_api.rest import ApiException


class TestInlineResponse20029InstrumentList(unittest.TestCase):
    """InlineResponse20029InstrumentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20029InstrumentList(self):
        """Test InlineResponse20029InstrumentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ib_web_api.models.inline_response20029_instrument_list.InlineResponse20029InstrumentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
