# Generated by Django 3.2.18 on 2023-03-07 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPIAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('enable', models.BooleanField(default=True, verbose_name='enable')),
                ('access_key', models.CharField(max_length=100, verbose_name='AccessKey')),
                ('secret_key', models.CharField(max_length=100, verbose_name='SecretKey')),
                ('expire_dt', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='expiration time')),
            ],
            options={
                'verbose_name': 'AccessKey',
                'verbose_name_plural': 'AccessKey',
                'db_table': 'openapi_auth',
            },
        ),
    ]
