# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HistoryresultBarsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        't': 'float',
        'o': 'float',
        'c': 'float',
        'h': 'float',
        'l': 'float',
        'v': 'float'
    }

    attribute_map = {
        't': 't',
        'o': 'o',
        'c': 'c',
        'h': 'h',
        'l': 'l',
        'v': 'v'
    }

    def __init__(self, t=None, o=None, c=None, h=None, l=None, v=None):  # noqa: E501
        """HistoryresultBarsData - a model defined in Swagger"""  # noqa: E501
        self._t = None
        self._o = None
        self._c = None
        self._h = None
        self._l = None
        self._v = None
        self.discriminator = None
        if t is not None:
            self.t = t
        if o is not None:
            self.o = o
        if c is not None:
            self.c = c
        if h is not None:
            self.h = h
        if l is not None:
            self.l = l
        if v is not None:
            self.v = v

    @property
    def t(self):
        """Gets the t of this HistoryresultBarsData.  # noqa: E501

        Time - Formatted in unix time in ms.  # noqa: E501

        :return: The t of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this HistoryresultBarsData.

        Time - Formatted in unix time in ms.  # noqa: E501

        :param t: The t of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._t = t

    @property
    def o(self):
        """Gets the o of this HistoryresultBarsData.  # noqa: E501

        Open - First price returned for bar value.  # noqa: E501

        :return: The o of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._o

    @o.setter
    def o(self, o):
        """Sets the o of this HistoryresultBarsData.

        Open - First price returned for bar value.  # noqa: E501

        :param o: The o of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._o = o

    @property
    def c(self):
        """Gets the c of this HistoryresultBarsData.  # noqa: E501

        Close - Last price returned for bar value.  # noqa: E501

        :return: The c of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._c

    @c.setter
    def c(self, c):
        """Sets the c of this HistoryresultBarsData.

        Close - Last price returned for bar value.  # noqa: E501

        :param c: The c of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._c = c

    @property
    def h(self):
        """Gets the h of this HistoryresultBarsData.  # noqa: E501

        High - High price returned for bar value.  # noqa: E501

        :return: The h of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this HistoryresultBarsData.

        High - High price returned for bar value.  # noqa: E501

        :param h: The h of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._h = h

    @property
    def l(self):
        """Gets the l of this HistoryresultBarsData.  # noqa: E501

        Low - Last price returned for bar value.  # noqa: E501

        :return: The l of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._l

    @l.setter
    def l(self, l):
        """Sets the l of this HistoryresultBarsData.

        Low - Last price returned for bar value.  # noqa: E501

        :param l: The l of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._l = l

    @property
    def v(self):
        """Gets the v of this HistoryresultBarsData.  # noqa: E501

        Volume - Traded volume for bar value.  # noqa: E501

        :return: The v of this HistoryresultBarsData.  # noqa: E501
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this HistoryresultBarsData.

        Volume - Traded volume for bar value.  # noqa: E501

        :param v: The v of this HistoryresultBarsData.  # noqa: E501
        :type: float
        """

        self._v = v

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoryresultBarsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoryresultBarsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
