
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-10T09:40:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d1e720fdcead40f3aef65cde0e4a05f0a7d8856",
 "version": "23.02.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
