
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-09T18:43:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe21f45e038fb6d08e34f570eb6e56a67758d3a6",
 "version": "v0.7.0a.post.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
