
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-09T19:22:07+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "efc4c20308a6b0105ed557261bec6759c3078f2d",
 "version": "2.1.1.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
