# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AllocationInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_class': 'object',
        'sector': 'object',
        'group': 'object'
    }

    attribute_map = {
        'asset_class': 'assetClass',
        'sector': 'sector',
        'group': 'group'
    }

    def __init__(self, asset_class=None, sector=None, group=None):  # noqa: E501
        """AllocationInner - a model defined in Swagger"""  # noqa: E501
        self._asset_class = None
        self._sector = None
        self._group = None
        self.discriminator = None
        if asset_class is not None:
            self.asset_class = asset_class
        if sector is not None:
            self.sector = sector
        if group is not None:
            self.group = group

    @property
    def asset_class(self):
        """Gets the asset_class of this AllocationInner.  # noqa: E501

        portfolio allocation by asset class  # noqa: E501

        :return: The asset_class of this AllocationInner.  # noqa: E501
        :rtype: object
        """
        return self._asset_class

    @asset_class.setter
    def asset_class(self, asset_class):
        """Sets the asset_class of this AllocationInner.

        portfolio allocation by asset class  # noqa: E501

        :param asset_class: The asset_class of this AllocationInner.  # noqa: E501
        :type: object
        """

        self._asset_class = asset_class

    @property
    def sector(self):
        """Gets the sector of this AllocationInner.  # noqa: E501

        portfolio allocation by sector  # noqa: E501

        :return: The sector of this AllocationInner.  # noqa: E501
        :rtype: object
        """
        return self._sector

    @sector.setter
    def sector(self, sector):
        """Sets the sector of this AllocationInner.

        portfolio allocation by sector  # noqa: E501

        :param sector: The sector of this AllocationInner.  # noqa: E501
        :type: object
        """

        self._sector = sector

    @property
    def group(self):
        """Gets the group of this AllocationInner.  # noqa: E501

        portfolio allocation by group  # noqa: E501

        :return: The group of this AllocationInner.  # noqa: E501
        :rtype: object
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this AllocationInner.

        portfolio allocation by group  # noqa: E501

        :param group: The group of this AllocationInner.  # noqa: E501
        :type: object
        """

        self._group = group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllocationInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllocationInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
