# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2009(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'main_acct': 'str',
        'acct_list': 'list[InlineResponse2009AcctList]'
    }

    attribute_map = {
        'main_acct': 'mainAcct',
        'acct_list': 'acctList'
    }

    def __init__(self, main_acct=None, acct_list=None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger"""  # noqa: E501
        self._main_acct = None
        self._acct_list = None
        self.discriminator = None
        if main_acct is not None:
            self.main_acct = main_acct
        if acct_list is not None:
            self.acct_list = acct_list

    @property
    def main_acct(self):
        """Gets the main_acct of this InlineResponse2009.  # noqa: E501

        The primary or parent account.  # noqa: E501

        :return: The main_acct of this InlineResponse2009.  # noqa: E501
        :rtype: str
        """
        return self._main_acct

    @main_acct.setter
    def main_acct(self, main_acct):
        """Sets the main_acct of this InlineResponse2009.

        The primary or parent account.  # noqa: E501

        :param main_acct: The main_acct of this InlineResponse2009.  # noqa: E501
        :type: str
        """

        self._main_acct = main_acct

    @property
    def acct_list(self):
        """Gets the acct_list of this InlineResponse2009.  # noqa: E501

        List of tradeable or Sub Accounts  # noqa: E501

        :return: The acct_list of this InlineResponse2009.  # noqa: E501
        :rtype: list[InlineResponse2009AcctList]
        """
        return self._acct_list

    @acct_list.setter
    def acct_list(self, acct_list):
        """Sets the acct_list of this InlineResponse2009.

        List of tradeable or Sub Accounts  # noqa: E501

        :param acct_list: The acct_list of this InlineResponse2009.  # noqa: E501
        :type: list[InlineResponse2009AcctList]
        """

        self._acct_list = acct_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2009, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2009):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
