# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20016(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'orders': 'list[InlineResponse20016Orders]',
        'snapshot': 'bool'
    }

    attribute_map = {
        'orders': 'orders',
        'snapshot': 'snapshot'
    }

    def __init__(self, orders=None, snapshot=None):  # noqa: E501
        """InlineResponse20016 - a model defined in Swagger"""  # noqa: E501
        self._orders = None
        self._snapshot = None
        self.discriminator = None
        if orders is not None:
            self.orders = orders
        if snapshot is not None:
            self.snapshot = snapshot

    @property
    def orders(self):
        """Gets the orders of this InlineResponse20016.  # noqa: E501


        :return: The orders of this InlineResponse20016.  # noqa: E501
        :rtype: list[InlineResponse20016Orders]
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this InlineResponse20016.


        :param orders: The orders of this InlineResponse20016.  # noqa: E501
        :type: list[InlineResponse20016Orders]
        """

        self._orders = orders

    @property
    def snapshot(self):
        """Gets the snapshot of this InlineResponse20016.  # noqa: E501

        If live order update is a snapshot  # noqa: E501

        :return: The snapshot of this InlineResponse20016.  # noqa: E501
        :rtype: bool
        """
        return self._snapshot

    @snapshot.setter
    def snapshot(self, snapshot):
        """Sets the snapshot of this InlineResponse20016.

        If live order update is a snapshot  # noqa: E501

        :param snapshot: The snapshot of this InlineResponse20016.  # noqa: E501
        :type: bool
        """

        self._snapshot = snapshot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20016, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20016):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
