#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2301-50-gca173ea9"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2301
#define NETGEN_VERSION_TWEAK 50
#define NETGEN_VERSION_HASH "gca173ea9"
#endif // NETGEN_VERSION_HPP_INCLUDED
