
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-09T23:54:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c26980302c74aed7d45e452d5bc2ac453848376",
 "version": "7.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
