# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class AttrType(object):
    """Enumeration."""

    NoAttr = 0
    Range = 1
    Reflectivity = 2
    SignalPhotons = 3
    NIRPhotons = 4
    ReflectivityNIR = 5
    AllAttr = 6
