# Generated by Django 4.1.3 on 2023-03-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schadmin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SChSetup",
        ),
    ]
