# Generated by Django 2.2.9 on 2022-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_timeout_for_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_carrier_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
