# Generated by Django 3.2.12 on 2022-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='imported',
            field=models.BooleanField(default=False, help_text='Flagged as imported records. if true auto calculation is disabled.'),
        ),
    ]
