
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-10T20:36:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "521cd56075a3e889cc1bba04643b724d960d3304",
 "version": "0.30.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
